CREATE DATABASE IT_DEPARTMENT;
DROP DATABASE IT_DEPARTMENT;
USE IT_DEPARTMENT;

CREATE TABLE IT(
            NAME VARCHAR(50),
            ID INT PRIMARY KEY,
            SALARY VARCHAR(50),
            DEPARTMENT VARCHAR(50)
);

ALTER TABLE IT
ADD CITY VARCHAR(50);

INSERT  INTO IT(NAME, ID, SALARY, DEPARTMENT,CITY)
VALUES
('RAM',1018,45000,'IT','HYDERABAD'),
('SYAM',1027,90000,'IT','DEHLI'),
('NEERAJ',1019,82000,'IT','DEHLI'),
('RAJU',1022,29000,'MARKETING','HYDERABAD'),
('DEPAK',1029,37000,'SALES','DEHLI'),
('NARESH',1026,50000,'SALES','VIZAG');



SELECT CITY, max(SALARY) AS EMP_SALARY 
FROM IT
GROUP BY CITY;
